### ISSUE TITLE
Возможность использование колонок с одинаковыми именами

### ISSUE THREAD

**Issue by s1lver** [pozitronik/yii2-grid-config#4]
При использовании в `label` колонок одинаковых имен, происходит слияние колонок в одну .

Пример:

Конфигурируем одинаковые колонки с **GridConfig** и **GridView**

1) **GridConfig**
```php
<?= \pozitronik\grid_config\GridConfig::widget([
	'id' => $id,
	'grid' => \kartik\grid\GridView::begin([
		'dataProvider' => $dataProvider,
		'filterModel' => $searchModel,
		'columns' => [
			[
				'label' => 'тест1',
				'attribute' => 'test_1',
				'options' => ['span' => 1],
				'headerOptions' => ['colspan' => 1]
			],
			[
				'label' => 'тест1',
				'attribute' => 'test_2'
			],
			[
				'label' => 'тест1',
				'attribute' => 'test_3'
			],
		]
	])
]) ?>
```
2) **GridView**
```php
<?= \kartik\grid\GridView::widget([
	'dataProvider' => $dataProvider,
	'filterModel' => $searchModel,
	'columns' => [
		[
			'label' => 'тест1',
			'attribute' => 'test_1',
			'options' => ['span' => 1],
			'headerOptions' => ['colspan' => 1]
		],
		[
			'label' => 'тест1',
			'attribute' => 'test_2'
		],
		[
			'label' => 'тест1',
			'attribute' => 'test_3'
		],
	]
]) ?>
```

В первом случае получаем
![Снимок экрана 2022-01-28 в 15 08 42](https://user-images.githubusercontent.com/4567634/151545092-6a51ed83-7369-4f8b-8ae1-47fcf129c22f.png)

И во втором
![Снимок экрана 2022-01-28 в 15 08 59](https://user-images.githubusercontent.com/4567634/151545208-e5f0ebef-ebab-4123-876a-b79549efa5c8.png)

Думаю стоит отказаться от формирования колонок только по `label` или добавить опцию `useVisibleColumns`. Хотя, во втором случае, опция имеет место только при использовании данного виджета в качестве общего в представлениях по умолчанию.

**Comment by pozitronik** [comment]
@s1lver 
Проверь, плз.

**Comment by s1lver** [comment]
> @s1lver Проверь, плз.

Вроде нормально работает

**Comment by pozitronik** [comment]
Вмержил в мастер.
