### ISSUE TITLE
Ошибка при использовании опции "Плавающий заголовок"

### ISSUE THREAD

**Issue by s1lver** [pozitronik/yii2-grid-config#5]
1) Открываем окно конфигурации колонок
2) Нажимаем вот сюда

![Снимок экрана 2022-02-09 в 15 08 48](https://user-images.githubusercontent.com/4567634/153198442-5531054c-9965-4c40-9bc1-ab1a4fb72c15.png)

3) Сохраняем
4) Получаем ошибку ниже

> pozitronik\grid_config\GridConfig::getId(): Return value must be of type string, null returned

**Comment by pozitronik** [comment]
@s1lver 
Поправил, проверяй

**Comment by s1lver** [comment]
Ну вообще странно, ведь id указано.

```php
$id = "{$modelName}-index-grid";
?>
<?= GridConfig::widget([
	'id' => $id,
	'grid' => GridView::begin([
		'id' => $id,
...
```

**Comment by pozitronik** [comment]
> Ну вообще странно, ведь id указано.
> 
> ```
> $id = "{$modelName}-index-grid";
> ?>
> <?= GridConfig::widget([
> 	'id' => $id,
> 	'grid' => GridView::begin([
> 		'id' => $id,
> ...
> ```

Нет, не странно. Это из-за логики фонового сохранения настроек: постинг опций принимает `ConfigController`, в котором создаётся модель `GridConfig`, загружающая пост. В этом случае id приходит не при инициализации, а после, отсюда и была ошибка.
